name: Angular CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest    
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2      

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependenciesnpm install and npm run CI commands
        run: npm i

      - name: Run tests
        run: npm run test

      - name: Run Build
        run: npm run build
